<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.knowy</groupId>
		<artifactId>parent</artifactId>
		<version>2.0.0</version>
		<relativePath>../../../pom.xml</relativePath>
	</parent>

	<artifactId>backend-api-spring</artifactId>
	<packaging>jar</packaging>

	<properties>
		<maven.compiler.source>21</maven.compiler.source>
		<maven.compiler.target>21</maven.compiler.target>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

	<dependencies>
		<dependency>
			<groupId>com.knowy</groupId>
			<artifactId>user-core</artifactId>
		</dependency>
		<dependency>
			<groupId>com.knowy</groupId>
			<artifactId>course-core</artifactId>
		</dependency>
		<dependency>
			<groupId>com.knowy</groupId>
			<artifactId>news-core</artifactId>
		</dependency>
		<dependency>
			<groupId>com.knowy</groupId>
			<artifactId>security-spring-jwt</artifactId>
		</dependency>

		<dependency>
			<groupId>com.knowy</groupId>
			<artifactId>persistence-spring-jpa</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-validation</artifactId>
		</dependency>
		<dependency>
			<groupId>com.knowy</groupId>
			<artifactId>xml-data-loader</artifactId>
		</dependency>
		<dependency>
			<groupId>com.knowy</groupId>
			<artifactId>xml-knowy-schemes</artifactId>
		</dependency>

		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
		</dependency>
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
		</dependency>

		<dependency>
			<groupId>io.swagger.core.v3</groupId>
			<artifactId>swagger-annotations</artifactId>
		</dependency>
		<dependency>
			<groupId>jakarta.validation</groupId>
			<artifactId>jakarta.validation-api</artifactId>
			<version>3.0.2</version>
		</dependency>
		<dependency>
			<groupId>jakarta.annotation</groupId>
			<artifactId>jakarta.annotation-api</artifactId>
		</dependency>
		<dependency>
			<groupId>org.openapitools</groupId>
			<artifactId>jackson-databind-nullable</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-config</artifactId>
			<version>6.4.12</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-web</artifactId>
			<version>6.4.12</version>
			<scope>compile</scope>
		</dependency>
    </dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<parameters>true</parameters>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<executions>
					<execution>
						<id>spring-build</id>
						<phase>package</phase>
						<goals>
							<goal>repackage</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.jacoco</groupId>
				<artifactId>jacoco-maven-plugin</artifactId>
				<version>0.8.13</version>
				<executions>
					<execution>
						<id>prepare-agent</id>
						<goals>
							<goal>prepare-agent</goal>
						</goals>
					</execution>
					<execution>
						<id>report</id>
						<phase>verify</phase>
						<goals>
							<goal>report</goal>
						</goals>
						<configuration>
							<outputDirectory>${project.build.directory}/jacoco-report</outputDirectory>
							<formats>
								<format>XML</format>
							</formats>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.openapitools</groupId>
				<artifactId>openapi-generator-maven-plugin</artifactId>
				<version>7.17.0</version>
				<executions>
					<execution>
						<goals>
							<goal>generate</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<inputSpec>${project.basedir}/src/main/resources/openapi.yaml</inputSpec>
					<generatorName>spring</generatorName>
					<apiPackage>com.knowy.server.api.controller</apiPackage>
					<modelPackage>com.knowy.server.api.dto</modelPackage>
					<configOptions>
						<interfaceOnly>true</interfaceOnly>
						<dateLibrary>java8</dateLibrary>
						<useSpringBoot3>true</useSpringBoot3>
						<useJakartaEe>true</useJakartaEe>
						<generateApiUtil>false</generateApiUtil>
						<skipDefaultInterface>true</skipDefaultInterface>
						<useBeanValidation>true</useBeanValidation>
					</configOptions>
					<globalProperties>
						<supportingFiles>false</supportingFiles>
					</globalProperties>
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>