services:
    web-server:
        build: server
        container_name: kn-server
        ports:
            - "8080:8080"
        networks:
            - knowy_net
        depends_on:
            -   postgres

    postgres:
        image: postgres:17
        container_name: kn-postgres17
        environment:
            POSTGRES_USER: knowy
            POSTGRES_PASSWORD: knowy
            POSTGRES_DB: knowydb
        ports:
            - "5434:5432"
        networks:
            - knowy_net
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
            - ./sql/init:/docker-entrypoint-initdb.d
            - ./sql:/sql

networks:
    knowy_net: