#!/usr/bin/env bash

set -e # exit on error

your_compose() {
	if [[ -n $(command -v podman) ]]; then
		podman compose "$@"
	elif [[ -n $(command -v compose) ]]; then
		compose "$@"
	else
		echo "You need to have podman or docker installed" >&2
		exit 1
	fi
}

run_operation() {
    if [[ "$1" == "up" || "$1" == "build" || "$1" == "restart" ]]; then
    	mvn verify --projects builds/knowy-thymeleaf-compose --also-make -Dmaven.test.skip
    fi

	if [[ "$2" == "default" || -z "$2" ]]; then
    	compose_file=$(find builds/knowy-thymeleaf-compose/target/ -name "compose.yaml")
    else
    	compose_file=$(find builds/knowy-thymeleaf-compose/target/ -name "compose-$2.yaml")
    fi
    your_compose -f "$compose_file" "$1" "${@:3}"
}

run_clean() {
	mvn clean verify --projects builds/knowy-thymeleaf-compose --also-make -Dmaven.test.skip
	for compose_file in $(find builds/knowy-thymeleaf-compose/target/ -name "compose*"); do
		your_compose -f "$compose_file" down -v
	done
}

print_help() {
    echo 'Usage:
    ./knowy <operation>

Operations:
    help                Print this help
    clean               Clean, re-compile, shutdown and remove all the containers, including their respective volumes
    up [profile]        Start the containers of the specified profile
    down [profile]      Shutdown and remove the containers of the specified profile
    restart [profile]   Restarts the containers of the specified profile

Profiles:
    default             Same as no profile; find an executes the default compose.yaml file
    dev                 The compose-dev.yaml file
    dev-onlydb          The compose-dev-onlydb.yaml file
    prod                The compose-prod.yaml

Examples:
    ./knowy up dev
    ./knowy down dev -v
    ./knowy restart dev'
    exit 0
}

case "$1" in
	"help")
		print_help
		;;
	"clean")
		run_clean
		;;
	*)
		run_operation "$@"
		;;
esac