spring:
    application:
        name: knowy-server
    datasource:
        url: jdbc:postgresql://localhost:5434/knowydb
        username: knowy
        password: knowy
    jpa:
        properties:
            hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: validate
server:
    port: 8080