spring:
    datasource:
        url: jdbc:postgresql://localhost:5434/knowydb
        username: knowy
        password: knowy
    mail:
        host: localhost
        port: 1025
        properties:
            mail:
                debug: true
server:
    error:
        include-message: always
        include-binding-errors: always