spring:
    config:
        import: "file:.env[.properties]"
    datasource:
        url: jdbc:postgresql://postgres:5432/knowydb
        username: knowy
        password: knowy
    jpa:
        properties:
            hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: validate
    mail:
        host: mailpit
        port: 1025
        properties:
            mail:
                protocol: smtp
                debug: false
                smtp:
                    auth: false
                    starttls:
                        enable: false
    jwt:
        key: ${JWT_SECRET_KEY}
server:
    port: 8080
    error:
        whitelabel:
            enabled: false
    servlet:
        session:
            timeout: 1m

management:
    endpoints:
        web:
            exposure:
                include: health,info