spring:
    mail:
        properties:
            mail:
                debug: true
server:
    error:
        include-message: always
        include-binding-errors: always
logging:
    level:
        org:
            springframework:
                security: debug
management:
    health:
        mail:
            enabled: false
