spring:
    datasource:
        url: ${DB_URL:jdbc:postgresql://localhost:5434/knowydb}
        username: ${DB_USER:knowy}
        password: ${DB_PASSWORD:knowy}
    jpa:
        properties:
            hibernate.dialect: ${DB_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
        hibernate:
            ddl-auto: validate
    mail:
        host: ${MAIL_HOST:localhost}
        port: ${MAIL_PORT:1025}
        properties:
            mail:
                protocol: smtp
                debug: false
                smtp:
                    auth: false
                    starttls:
                        enable: false
    jwt:
        key: ${JWT_SECRET_KEY:default-password-that-must-be-replaced-in-public-deploys}
server:
    port: 443
    ssl:
        enabled: true
        key-store: classpath:${SSL_KEYSTORE:keystore.p12}
        key-store-password: ${SSL_KEY:default-keystore-must-be-replaced-in-public-deploys}
        key-store-type: ${SSL_KEYSTORE_TYPE:PKCS12}
        key-alias: ${SSL_KEY_ALIAS:knowy-server}
    error:
        whitelabel:
            enabled: false
    servlet:
        session:
            timeout: 1d

management:
    endpoints:
        web:
            exposure:
                include: health,info
