name: Deploy to Production

on:
    push:
        tags: [ "v*" ]
        branches: [ main ]
    workflow_dispatch:

jobs:
    build-analyze-deploy:
        runs-on: self-hosted
        env:
            SSL_KEY: ${{ secrets.SSL_KEY }}
            JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Set up JDK 21
                uses: actions/setup-java@v4
                with:
                    distribution: 'temurin'
                    java-version: '21'
                    cache: 'maven'

            -   name: Verify Java version
                run: java -version

            -   name: Build, Test & SonarQube Analysis
                working-directory: ./server
                env:
                    SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
                    SONAR_PROJECT_KEY: ${{ vars.SONAR_PROJECT_KEY }}
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                run: |
                    mvn clean verify
                    mvn sonar:sonar \
                      -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
                      -Dsonar.host.url=${SONAR_HOST_URL} \
                      -Dsonar.login=${SONAR_TOKEN} \
                      -Dsonar.coverage.jacoco.xmlReportPaths=target/jacoco-report/jacoco.xml

            -   name: Deploy with Docker Compose
                run: |
                    docker-compose down -v
                    docker-compose -f compose-prod.yaml down -v
                    docker-compose -f compose-prod.yaml up -d --build